on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: '0 0 * * 0'
  - cron: '0 0 * * 1-6'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - name: SAST and SSC
      if: github.event.schedule != '0 0 * * 1-6'
      run: semgrep ci
    - name: SSC
      if: github.event.schedule != '0 0 * * 0'
      run: semgrep ci --supply-chain

